[package]
name = "xor"
version = "0.1.3"
edition = "2024"

[dependencies]
anyhow = "^1"
tokio = { version = "^1.49", features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "sync",
    "signal",
    "time",
] }
supershorty = "^0.2.1"
env_logger = { version = "^0.11", default-features = false, features = [
    "humantime",
] }
log = "^0.4"
rayon = "^1.11"
crossbeam-queue = "^0.3.12"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
